[Feat] Pls 24 create scrap page layout
Pleisure/frontend pull request #1
Opened 2023-08-08 11:05 UTC by hyunjoo1130

## :: 최근 작업 주제 
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 레이아웃

<br />

## :: 구현 사항 설명
1. 레이아웃 1차 완료
- 필요할 것 같은 컴포넌트 생성 및 분리

<br />

## :: 나만의 포인트

<br />

2023-08-09 13:26 UTC, yulmucha commented on app/scrap/page.tsx
> +        </div>
이 부분도 아래 `CategoryPopUp`이나 `LeisureStorePost`처럼 컴포넌트화하면 가독성이 꽤 좋아지지 않을까 싶은 생각이 들어요.

2023-08-09 13:26 UTC, yulmucha commented on app/scrap/page.tsx
> +'use client';
아마도 카테고리 버튼 클릭했을 때 페이지 어둡게 하는 것 때문에 전체를 클라이언트 컴포넌트로 만드신 걸까요?

'use client'를 지워서 여기 `page.tsx`의 가장 최상위 컴포넌트(`Scrap`)를 '서버 컴포넌트'로 둔 채로도 똑같이 동작하도록 리팩토링해 보시는 것도 좋은 경험이 될 것 같아요!

근데 저도 궁금해서 같이 고민해 봐도 좋을 것 같네요. @daeunkim212

2023-08-09 13:26 UTC, yulmucha commented on app/components-hj/scrap/CategoryPopUp.tsx
> +      {/* pop-up */}
팝업이 굉장히 부드럽게 잘 오르락내리락 하네요 👍
다만 저만 그렇게 보이는 건지 모르겠지만, 첫 페이지 로딩 시 이미 올라와 있다가 바로 내려가는 것 같습니다. 혹시 의도하신 부분인가요?

2023-08-09 13:26 UTC, yulmucha commented on app/components-hj/scrap/LeisureStorePost.tsx
> +export default function LeisureStorePost() {
나중에 API 연결만 하면 완성되도록 하려면
외부로부터 데이터를 받아서 렌더링하는 컴포넌트로 만들어 둬야 할 것 같아요

2023-08-11 12:58 UTC, hyunjoo1130 commented on app/components-hj/scrap/CategoryPopUp.tsx
> +      {/* pop-up */}
엇 그러네요 ! 미처 확인을 못했네요 ㅜ 수정해보도록 하겠습니다 !

페이지 이동하여 첫 렌더링 시에는, 보이지 않는데
새로고침 할 때마다 애니메이션이 미리 보이는 문제가 있네요!

2023-08-11 12:58 UTC, hyunjoo1130 commented on app/components-hj/scrap/LeisureStorePost.tsx
> +export default function LeisureStorePost() {
넵 ! 그러는게 좋겠네요 !
수정 완료 했습니다!

2023-08-11 12:58 UTC, hyunjoo1130 commented on app/scrap/page.tsx
> +'use client';
오 네! 그 부분은 간단히 리팩토링 하여서 수정됐습니다!
Scrap.tsx 는 서버컴포넌트로 유지하면서, CategoryPopUp 만 클라이언트 컴포넌트로 작동되도록 수정하였습니다.

2023-08-11 12:58 UTC, hyunjoo1130 commented on app/scrap/page.tsx
> +        </div>
네! 컴포넌트화 시켜 분리했습니다!

2023-08-12 15:19 UTC, daeunkim212 requested changes

2023-08-12 15:19 UTC, daeunkim212 commented on app/components-hj/scrap/CategoryPopUp.tsx
> +      {/* pop-up */}
저도 공감해요! 팝업이 스무스하게 움직이는 거 너무 좋은 것 같아요!! 👏👏👏

2023-08-12 15:19 UTC, daeunkim212 commented on app/components-hj/scrap/CategoryPopUp.tsx
width가 448px(w-md)일때로 팝업 가로 크기가 고정이 되서 그보다 작은 화면에서 볼때는 오른쪽이 잘려서 나와요. 수정 부탁드려요!

2023-08-12 15:19 UTC, daeunkim212 commented on app/components-hj/scrap/LeisureStorePost.tsx
> +            <span className="ml-1 mr-3">4.8</span>
font bold로 변경 부탁드려용!

2023-08-12 15:19 UTC, daeunkim212 commented on app/scrap/page.tsx
> +      </section>
화면의 width가 416px일때부터 레저 포스트끼리 붙어요. width가 416px보다 작으면 두 포스트가 겹쳐져용!

2023-08-12 15:19 UTC, daeunkim212 commented on app/scrap/page.tsx
scrap대신 scraps로 이름을 짓는게 더 좋을 것 같아요.

2023-08-12 15:58 UTC, yulmucha commented on app/components-hj/scrap/LeisureStorePost.tsx
> +export default function LeisureStorePost() {
혹시 그 수정 내용을 이 PR의 브랜치(PLS-24-Create-scrap-page-layout)에 커밋하고 푸쉬하셨나요?
만약 안 하셨으면 그렇게 해 주시길 부탁드립니다 (PR에 수정 완료된 내용이 안 보여서요)

2023-08-13 14:25 UTC, hyunjoo1130 commented on app/components-hj/scrap/LeisureStorePost.tsx
> +export default function LeisureStorePost() {
아직 푸쉬 안해가지구, 안보이셨을거에요! 푸쉬하고 말씀드릴게요!

2023-08-13 14:25 UTC, hyunjoo1130 commented on app/components-hj/scrap/CategoryPopUp.tsx
팝업이 position fixed 라, 부모가 브라우저인 상태에요.
반응형을 주려면, 일일히 다 수정해야하는 것 같아서 약간 추후로 미뤄야하지 않을까 싶어요 ㅜ_ㅜ
아니면 제가 모르는 다른 방법이 있을까요 ?.?

2023-08-13 14:25 UTC, hyunjoo1130 commented on app/components-hj/scrap/LeisureStorePost.tsx
> +            <span className="ml-1 mr-3">4.8</span>
변경 완료!

2023-08-13 14:25 UTC, hyunjoo1130 commented on app/scrap/page.tsx
오호 그렇겠네요! 넵

2023-08-13 14:25 UTC, hyunjoo1130 commented on app/scrap/page.tsx
> +      </section>
네! 이 부분 너비를 %로 바꿔서, 자동 조정되도록 수정완료했씁니다!

2023-08-13 14:40 UTC, daeunkim212 commented on app/components-hj/scrap/CategoryPopUp.tsx
일단 40번째줄에 ul classname 중 'w-[27.75rem]' 대신에 'w-full max-w-md'로 변경하시면 해결 가능해요! 일단 이 방법으로 수정 부탁드릴께요

2023-08-13 15:03 UTC, hyunjoo1130 commented on app/components-hj/scrap/CategoryPopUp.tsx
흑흑 일단 수정했습니다!
max-w-md 에 고정이고, 그 밑으로는 아직도 넘치고 있긴해요!

2023-08-13 20:01 UTC, daeunkim212 approved these changes

2023-08-13 20:01 UTC, daeunkim212 commented on app/components-hj/scrap/CategoryPopUp.tsx
수고하셨어요!! 차차 수정해 나가도록 해봐용!

2023-08-13 20:03 UTC, daeunkim212 approved these changes

2023-08-13 20:05 UTC, daeunkim212 approved these changes

2023-08-15 14:28 UTC, yulmucha approved these changes

2023-08-18 09:41 UTC, merged