[Feat] Create leisure detail page layout
Pleisure/frontend pull request #2
Opened 2023-08-08 11:07 UTC by hyunjoo1130

## :: 최근 작업 주제 
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 레이아웃

<br />

## :: 구현 사항 설명
1. 레이아웃 1차 완료
- 필요할 것 같은 컴포넌트 생성 및 분리

<br />

## :: 나만의 포인트

<br />

2023-08-10 19:48 UTC, daeunkim212 requested changes

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/StorePost.tsx
> +            <span className="ml-1 mr-3">4.8</span>
여기에 들어가는 숫자는 bold로 변경해주세요

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/StorePost.tsx
> +      `}</style>
이 부분을 따로 뺀 이유는 무엇인가요?

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/PhotoSlide.tsx
> +    <div className={`flex gap-${gap} my-4 overflow-hidden`}>
저도 이것때문에 애를 좀 먹었는데요 `(백틱)${}`(백틱) <= 이거를 썼을때 style이 잘 먹히지 않더라구요. 이 부분은 해결방법을 찾아봐야 할 것 같아요.

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/PhotoSlide.tsx
> +type PropsType = {
사진의 사이즈도 prop으로 받으면 좋을 것 같아요.

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/PhotoSlide.tsx
photo와 slide를 각각의 다른 컴포넌트로 만들면 재사용성이 높아져요!

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/PhotoSlide.tsx
이 컴포넌트는 가로로 스크롤 할 수 있는 컴포넌트를 말씀하신 것 같아요. slide는 가로 세로 둘다 할 수 있기때문에 slide의 방향도 prop으로 추가해주면 좋을 것 같아요. 아니면 HorizontalSlide와 VerticalSlide 두개로 따로 만드는 방법도 있어요

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/PhotoSlide.tsx
> +  imgUrl: string;
하나의 사진이 아닌 여러가지의 사진을 받아서 보여줄 예정이기 때문에 imgUrls: string[]로 받거나 아니면 photos: Photo[] 를 prop으로 받는 것이 좋아보여용. 여기서 Photo 타입은 photoUrl, photoPostUrl를 포함하구요.

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/CEOInfo.tsx
> +];
데이터를 prop으로 받았다고 가정하고 위의 형식으로 바꿔주는 function을 만들어보면 나중에 데이터 받게 됐을 때 편할 것 같아요.

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/Header.tsx
> +      <div className="flex cursor-pointer">
클릭할 수 있는 범위를 width와  height를 최소 36px로 정해주는 게 좋을 것 같아요. 모바일 폰에서 버튼이 너무 작으면 터치하기 힘들 수 있어요

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/Header.tsx
> +      <p className="w-full text-xl font-bold text-center">{title}</p>
StorePost의 제목처럼 제목이 너무 길어서 줄이 넘어가게 되면 글씨를 생략하고 마지막에 ... 처리 해주세요

2023-08-10 19:48 UTC, daeunkim212 commented on app/components-hj/leisure-detail/Nav.tsx
컴포넌트 이름이랑 파일 이름을 통일시켜주세요

2023-08-10 19:48 UTC, daeunkim212 commented on app/leisure-detail/page.tsx
> +      <Nav />
위아래로 스크롤 할때 일단은 sticky를 써서 Nav가 상단에 닿았을 경우에 더이상 넘어가지 않도록 해주세요.

2023-08-10 19:48 UTC, daeunkim212 commented on public/images/leisure-detail/test-profile-img.png
너모 귀엽네용<3 <3

2023-08-14 10:02 UTC, hyunjoo1130 commented on app/components-hj/leisure-detail/StorePost.tsx
> +      `}</style>
-webkit- 관련 tailwind 속성을 잘 못찾겠어서, 일단 style 로 직접 주었습니다~!

2023-08-15 13:30 UTC, hyunjoo1130 commented on app/components-hj/leisure-detail/PhotoSlide.tsx
> +    <div className={`flex gap-${gap} my-4 overflow-hidden`}>
https://velog.io/@arthur/Tailwind-CSS-%EC%97%90%EC%84%9C-%EB%8F%99%EC%A0%81%EC%9C%BC%EB%A1%9C-%ED%81%B4%EB%9E%98%EC%8A%A4-%ED%95%A0%EB%8B%B9%ED%95%98%EA%B8%B0

이 블로그 참고해보시면 해결에 도움이 될 것 같아요! 저희랑 같은 이슈 내용이에요! 
결론은 tailwindCSS 는 클래스네임 동적할당을 인식을 못한대요 ... 😂

2023-08-15 15:21 UTC, yulmucha requested changes
늦어서 죄송합니다! 😓
레이아웃 깔끔하게 잘 잡으시네요👍👍 (부럽)
URL 관련해서만 다시 봐 주시면 될 것 같습니다

2023-08-15 15:21 UTC, yulmucha commented on app/leisure-detail/page.tsx
상세 페이지 URL은 보통 아래와 같은 식이에요.
오늘의집 `/productions/1865952`
무신사 `/goods/2442409`
네이버쇼핑 `/artmu/products/8237319688`

그래서 URL이 `/leisures/12345`와 같은 식이 되어야 하지 않을까 싶어요.

이유가 궁금하시면 아래 영상을 참고해 보시면 좋을 것 같아요!
[REST API가 뭔가요?](https://youtu.be/iOueE9AXDQQ)

방법은 제가 컨플루언스에 정리한 글 [Dynamic Routes](https://project-pleisure.atlassian.net/wiki/spaces/SD/pages/1179703/Routing#Dynamic-Routes)를 참고해 주세요.

2023-08-16 05:21 UTC, hyunjoo1130 commented on app/leisure-detail/page.tsx
넵! 안그래도 이부분 고민중이었는데, 다은님이랑 혹시 충돌날까봐서 그대로 두고 있었어요!
금요일날 다은님이랑 이야기해서 폴더명 합의보도록 하겠습니당당

2023-08-18 08:37 UTC, daeunkim212 commented on app/components-hj/leisure-detail/StorePost.tsx
> +      `}</style>
아하 그렇군요! https://tailwindcss.com/docs/browser-support <-- 여기에 방법이 있는 것 같아서 읽어보고 dev 브랜치에 적용해보도록 할께요!

2023-08-18 08:38 UTC, daeunkim212 approved these changes

2023-08-18 09:29 UTC, yulmucha approved these changes

2023-08-18 09:48 UTC, merged