Pls 10 create leisure main page layout
Pleisure/frontend pull request #3
Opened 2023-08-08 15:43 UTC by daeunkim212

##### **📓 My Taks**
✨Creates Components
- atoms/Button: button component.
- atoms/Container: container component that does layout stuff.
- atoms/Dropdown: dropdown component.
- atoms/Pagination: little pagination for carousel banner.
- atoms/Spacing: transparent spacing to create space between components instead of margin and padding.
- atoms/Txt: text component to limit styles of text.
- molecules/Banner: banner component, need to be implement carousel.
- molecules/LeisureCategory: leisure category component for category button in leisure main page.
- molecules/Section: section component of white background with shadow.
- molecules/StoreCard: store card component for store list view.
- organisms/Footer: footer component which will be placed at the bottom of the page. it is nav bar for now but will be added more types of footer.
- organisms/Header: header component which will be placed at the top of the page. more types of header will be added.
- organisms/PageLayout: page layout for mobile pages.

✨Creates Hooks
- useBanners: (not implement yet) hooks to get banners data
- useLeisureCategories: (not implement yet) hooks to get all leisure categories data
- useLeisureStores: (not implement yet) hooks to get leisure stores list data

✨Creates Common Functions
- joinString: join all the input strings with a space between them
- roundReviewCount: if number of reviews is over 999, text changes to '999+'

✨Creates Leisure Page
- layout: nothing done
- page: implement leisure main page

2023-08-09 06:30 UTC, yulmucha submitted a review, later dismissed

2023-08-09 06:58 UTC, yulmucha commented on app/dd-components/molecules/StoreCard.tsx
> +            <Txt typography='caption'>리뷰</Txt>
"리뷰"라는 단어가 생략되어도 괜찮지 않을까 싶어요

2023-08-09 07:05 UTC, yulmucha requested changes

2023-08-09 07:05 UTC, yulmucha commented on app/dd-components/atoms/Button.tsx
> +const TYPE_VARIANTS = {
constant들은 function보다 위에 위치하는 게 가독성이나 컨벤션 측면에서 좋을 것 같아요

2023-08-09 07:08 UTC, daeunkim212 commented on app/dd-components/atoms/Button.tsx
> +const TYPE_VARIANTS = {
스타일 constant라서 일부로 아래에 두었습니다.

2023-08-09 07:42 UTC, hyunjoo1130 requested changes
컴포넌트 확장성이 crazy 하네요 >_<
수고하셨습니다 !
많이 뺏겨서 제 코드에도 적극적으로 적용시켜보겠습니다 ㅜ_ㅜ 할 수 있을지 모르겠지만 ...

components 파일명 수정부탁드립니다 ! ( 좀 더 효율적인 구별과 정렬을 위해 )
```dd-components``` => ```components-dd```

2023-08-09 07:42 UTC, hyunjoo1130 commented on app/leisures/page.tsx
> +        <Spacing key={`spcaing1`} size={40} />
오타가 있는 것 같습니다. 'spcaing1' -> 'spacing1' 😂

2023-08-09 07:42 UTC, hyunjoo1130 commented on app/dd-components/organisms/PageLayout.tsx
> +  let bodyHeight = 'h-[calc(100vh-172px)]';
calc 한번 강의 부탁드립니다 .... 😭

2023-08-09 07:42 UTC, hyunjoo1130 commented on app/dd-components/organisms/Footer.tsx
> +    <div className='w-full h-full bg-white border border-t shadow-md rounded-t-md'>
저는 개인적으로 웹 표준 태그 사용을 선호하는데,
```<div>``` 보다는 ```<footer>``` 태그를 사용하면 어떨까요 ?

컴포넌트 Footer 는 코딩하는 저희 입장에서는 가독성이 좋아서 확실히 좋은 것 같아요.
근데 실제 브라우저에서 개발자도구를 열어서보면 다 ```<div>```로만 떠서, 가독성이 떨어지더라구요!
웹 표준 태그 사용을 추천드립니다!

2023-08-09 07:42 UTC, hyunjoo1130 commented on app/dd-components/molecules/Section.tsx
> +    <div className='w-full bg-white shadow-md'>
웹 표준 태그, 시맨틱 태그로 ```<div>```를 ```<section>```으로 대체하시면 어떨까요 ?

2023-08-09 07:42 UTC, hyunjoo1130 commented on app/dd-components/organisms/Header.tsx
> +    <div className='w-full h-full bg-white border-b pt-[44px]'>
웹 표준 태그, 시맨틱 태그로 ```<div>```를 ```<header>```으로 대체하시면 어떨까요 ?

2023-08-09 07:42 UTC, hyunjoo1130 commented on app/leisures/page.tsx
> +            </Container>
Container 랑 Dropdown 이 좀 멀리 떨어져 있는 것 같더라구요 !
좀 더 서로 붙여주시면 더 예쁠 것 같습니다 :)

2023-08-09 07:53 UTC, yulmucha approved these changes

2023-08-09 07:53 UTC, yulmucha commented on app/leisures/page.tsx
> +          <Dropdown isOpen={filterOpen}>
추상화 잘하셨네요!👍 안 그래도 제 코드에는 `div`들이 너무 많아서 가독성이 너무 떨어진다 싶었는데

2023-08-09 07:53 UTC, yulmucha commented on app/dd-libs/utils/joinStrings.ts
> +export default function joinStrings(...strings: string[]) {
좀 더 추상적으로 기능을 설명하는 이름으로 짓는 게 좋지 않을까 싶네요. 예를 들면, `joinClassNames()`?

2023-08-09 07:53 UTC, yulmucha commented on app/dd-components/molecules/StoreCard.tsx
> +            <svg
⭐️도 컴포넌트화해 주시면 가독성이 더 좋아질 것 같아요

2023-08-09 08:08 UTC, yulmucha commented on app/dd-components/molecules/StoreCard.tsx
> +            </svg>
⭐️도 컴포넌트화해 주시면 가독성이 더 좋아질 것 같아요

2023-08-12 14:55 UTC, daeunkim212 commented on app/dd-components/organisms/PageLayout.tsx
> +  let bodyHeight = 'h-[calc(100vh-172px)]';
넵!! 정리해서 공유해드릴께요!!

2023-08-15 13:18 UTC, hyunjoo1130 approved these changes

2023-08-15 13:18 UTC, hyunjoo1130 commented on app/components-dd/organisms/Footer.tsx
> +            <svg
제가 일단 아이콘 컴포넌트 재활용 때문에 따로 분리해놨는데, 나중에 같이 써도 좋을 것 같아요! 
다은님 스타일로 만들어서 사용하셔도 되구용 ㅎㅎ 만들기 귀찮으실까봐

2023-08-15 13:18 UTC, hyunjoo1130 commented on app/components-dd/organisms/Header.tsx
> +          <Link href='/bookmarks' className='items-center w-8 p-1 rounded-md hover:bg-gray-100 aspect-square'>
스크랩 아이콘 누르면, 라우팅 주소가 bookmarks 로 이동되는데,
저는 지금 scraps 로 해놨거든요 !! bookmarks 로 바꿀까요 ?.?
bookmarks 가 더 좋은 것 같긴하네용

2023-08-18 08:28 UTC, merged