[Feat] Pls-23 :  Create leisure reviews page
Pleisure/frontend pull request #5
Opened 2023-08-19 13:59 UTC by yulmucha

## :: 레저 리뷰 페이지 구현에 필요한 컴포넌트 구현 및 페이지 구현

### 구현 사항 설명
✨ 총 별점 요약 표시

✨ 정렬 기준 선택 버튼
- 클릭 시 드롭다운 열기
- 이미 선택되어 있는 정렬 기준은 체크 표시 및 클릭 불가
- 다시 클릭 시 드롭다운 닫기

✨리뷰 내용 표시
- 60자를 넘어갈 경우 60자까지 자르고 "...더보기"와 함께 표시
- 내용 부분 클릭 시 자르기 전의 원본 내용을 "접기"와 함께 표시
- 다시 클릭 시 처음 상태(~60자 + "...더보기")로 돌아감
<br/>

### 미구현 사항 설명
✨ 리뷰 사진
- 여러 개의 사진이 포함되어 있을 때, 특정 개수 표시 및 특정 개수를 초과하면 마지막 사진에 음영과 함께 "+N"(예: "+2") 표시 (더보기의 역할)
- 사진 클릭 시 사진 확대
<br/>

2023-08-20 14:26 UTC, daeunkim212 commented on app/components-yul/ReviewContent.tsx
더보기와 접기가 잘 작동하네요! 👍 
대신 더보기가 있어야하는 기준이 있어야 할 것 같아요. 더보기로 글씨를 줄이지 않아도 되는 부분에도 글씨가 줄어있더라구요! 글자수 대신에 텍스트를 감싸는 컴포넌트의 width를 기준으로 더보기를 입히면 좋을 것 같아요. 
![스크린샷 2023-08-20 오후 9 31 21](https://github.com/Pleisure/frontend/assets/37150882/3a94319a-f81f-451a-b9cc-b25f32876e1d)
![스크린샷 2023-08-20 오후 9 31 12](https://github.com/Pleisure/frontend/assets/37150882/f145bdcc-4b4b-4fea-b31f-0622bff81c1d)

2023-08-20 14:26 UTC, daeunkim212 commented on app/components-yul/SortButton.tsx
> +const 추천순 = '추천순';
이 부분은 따로 plain object로 만들어서 가져다 사용하는게 좋을 것 같아요.

```Typescript
const SORTING_OPTIONS = {
    최신순: {name: '최신순', query:'recent'},
    추천순: {name: '추천순', query:'suggest'},
    인기순: {name: '인기순', query:'popular'},
}
```

2023-08-20 14:26 UTC, daeunkim212 commented on app/reviews/fetcher.tsx
와우 이거 너무 잘하신 것 같아요!! 👏👏👏👏👏

2023-08-20 14:26 UTC, daeunkim212 commented on app/reviews/page.tsx
> +          <span>⭐️</span>
SVG 하늘색 별 아이콘으로 변경햅주세요

2023-08-20 14:26 UTC, daeunkim212 commented on app/reviews/page.tsx
> +                <a href="#">신고</a>
a tag 대신 버튼을 사용하는게 좋을 것 같아요. 신고는 페이지 이동이 아닌 모달을 띄울 예정입니다.
그리고 a 태그 대신에 Link 태그를 쓰시는 걸 추천해용!

2023-08-20 14:26 UTC, daeunkim212 commented on app/reviews/page.tsx
> +          </div>
컴포넌트로 만드는게 가독성이 더 좋아질 것 같아요 👍

2023-08-21 06:48 UTC, hyunjoo1130 requested changes
오 몬가 전반적으로 코드가 백엔드 느낌이 물씬나고, 컴팩트하고 짧네요!
신기해용! 수고하셨습니다 ~_~

2023-08-21 06:48 UTC, hyunjoo1130 commented on app/reviews/page.tsx
> +          <div>
map 돌리는 부분이 다 빨간줄인데, 최상위 태그에 key 속성만 추가해주면 없어집니다!
id 같은 거에요. map 돌리는 부분마다 key속성 추가해주세요!
value 값은 고유값이여야 합니다.
받는 데이터에 id 값을 사용하거나, map돌리는 배열의 index 값을 사용해도 됩니다. ( map 메서드의 파라미터 두번째자리가, index 입니다!)

```typescript
{reviews.map((review, index) => (
   <div key={index}>
   ...
   </div>
))}
```

2023-08-21 06:48 UTC, hyunjoo1130 commented on app/reviews/page.tsx
> +          <span>⭐️</span>
svg태그인 별 아이콘으로 변경하고 map 돌리시면 돼용!

2023-08-21 06:48 UTC, hyunjoo1130 commented on app/components-yul/RelativeTime.tsx
> +}
오호 라이브러리를 쓰셨군용
저도 그럼 작성오차일 dayjs 로 구현하도록 하겠습니다 ! !

2023-08-21 06:48 UTC, hyunjoo1130 commented on app/components-yul/ReviewContent.tsx
> +  const [content, setContent] = useState(croppedContent);
라인 17, 18 useState가 빨간줄이네요!
useState는 최상단에서 호출이 되어야 한다고 하네요. 렌더링순서와 호출순서가 정확히 일치해야 한대요!
최상단으로 옮겨주세요!

2023-08-21 06:48 UTC, hyunjoo1130 commented on app/components-yul/ReviewContent.tsx
> +        <p className="text-gray-500">접기</p>
오우 저는 더보기 구현만 해놓구, 펼쳤다 접는건 못했는데 둘다 하셨네요 ! 수고하셨습니당

2023-08-21 06:49 UTC, hyunjoo1130 approved these changes

2023-09-03 00:42 UTC, yulmucha commented on app/components-yul/ReviewContent.tsx
> +  const [content, setContent] = useState(croppedContent);
ESLint extension 설치하니까 저도 똑같은 빨간 줄 뜨네요.
early return하는 조건문이 위에 있어서 그렇군요.
>  You can only call Hooks at the top of your components (or other Hooks). If you want to use useState in a condition or a loop, extract a new component and put it there.
[공식문서 Using Hooks](https://react.dev/learn#using-hooks)

2023-09-03 08:48 UTC, daeunkim212 approved these changes

2023-09-03 15:46 UTC, merged