[Feat] Pls-91 : [FE] Show reviewers age by age group
Pleisure/frontend pull request #8
Opened 2023-08-25 01:51 UTC by hyunjoo1130

## :: 리뷰 작성자의 나이를 연령대로 렌더링 ( ex - 10대, 20대, 30대 ... )

### 구현 사항 설명

**✨ Add show reviewers age by age group ```ReviewArticle.tsx```**
-  number 타입으로 들어오는 리뷰작성자의 나이를 ```toString()```메서드로 문자열로 변환시켜, 첫번째 숫자 요소를 배열 접근식으로 추출하여 뒤에 문자열 **‘+0대’** 로 붙여주어 구현
- review rating (별점) 이 1~5 의 숫자로 들어오기 때문에, 그 숫자에 맞춰 배열을 생성하여 그 숫자로 배열을 채워준 뒤,  해당 배열을 ```map```을 돌려 별이 갯수에 맞게 렌더링되게끔 구현.

**♻️ Refactor**

```Button.tsx```
- navigating을 위해 Link태그 추가

```Slide.tsx / Photo.tsx```
- Slide에서 fetch 데이터를 받을 예정이기 때문에 Slide 컴포넌트 자체에서 imgUrl prop을 받지 않고,
데이터를 가지고 map을 돌릴 Photo 컴포넌트에서 imgUrl prop을 받는 것이 더 알맞다고 판단하여 수정

```Review.tsx```
- API spec 의 데이터 형태와 맞춰서 fake data를 만들어 연습삼아 데이터 이름을 맞추고 렌더링 시켜보았음

```page.tsx```
- fake data에 interface type 지정. API spec을 기본으로 하고, 그 외 내가 임의로 만들어놓은 객체타입들.

<br/>

### 코드 기록
- 나이 연령대
```typescript
`${reviewWriterAge.toString()[0]}0대`
```

- 별점
```typescript
const starsCnt = new Array(storeReviewRating).fill(storeReviewRating)

{starsCnt.map((v, i) => {
  return (
      <span key={i}>
         <Icon ... />
      </span>
    );
  })}
```
<br/>

### 브랜치 회고
<br/>

2023-08-27 12:53 UTC, daeunkim212 approved these changes

2023-08-27 12:53 UTC, daeunkim212 commented on app/components-hj/leisure-detail/organisms/ReviewArticle.tsx
> +                {`${reviewWriterAge.toString()[0]}0대`} /{' '}
너무 잘 바꿔주셨어요! 이걸 function으로 따로 만들어서 사용하면 가독성이 더 좋아질 것 같아요! 😄

2023-08-28 07:10 UTC, yulmucha requested changes
9세 이하가 리뷰를 작성할 확률이 낮을 것 같긴 하지만 원천적으로 가입을 막지 않는 한 충분히 있을 수 있다고 생각해요.
그래서 8세가 80대, 9세가 90대로 보이는 건 잡고 넘어가야 할 것 같습니다.

2023-08-28 07:10 UTC, yulmucha commented on app/components-hj/leisure-detail/organisms/ReviewArticle.tsx
> +                {`${reviewWriterAge.toString()[0]}0대`} /{' '}
9세 이하인 경우에는 제대로 표시되지 않는 것 같아요.
예) 8세 -> 80대, 9세 -> 90대

2023-08-28 07:10 UTC, yulmucha commented on app/components-hj/leisure-detail/organisms/ReviewArticle.tsx
> +  const starsCnt = new Array(storeReviewRating).fill(storeReviewRating);
꼭 안 바꾸셔도 되고 그냥 참고용으로 남겨 보아요.

이미 아실 수도 있지만,
`const starsCnt = Array.from({ length: storeReviewRating });`
이렇게 하면 `.fill()`을 안 써도 됩니다.

2023-08-28 10:25 UTC, hyunjoo1130 commented on app/components-hj/leisure-detail/organisms/ReviewArticle.tsx
> +                {`${reviewWriterAge.toString()[0]}0대`} /{' '}
헉 생각이 짧았네요! 감사합니다~ 수정하도록 하겠습니다!

2023-08-28 10:26 UTC, hyunjoo1130 commented on app/components-hj/leisure-detail/organisms/ReviewArticle.tsx
> +  const starsCnt = new Array(storeReviewRating).fill(storeReviewRating);
와우 from은 써보지 않아서 몰랐어요! 이참에 공부해야겠네요 감사합니다!!!

2023-08-28 13:18 UTC, hyunjoo1130 commented on app/components-hj/leisure-detail/organisms/ReviewArticle.tsx
> +  const starsCnt = new Array(storeReviewRating).fill(storeReviewRating);
이렇게 해봤는데 안되네요ㅠ ?! 그냥 new Array() 말씀하신걸까요?
그리구, 생각해보니 빈별도 나타내줘야 해서 일단 기존으로 가야할 것 같네요 ㅎㅎ

2023-09-01 12:06 UTC, yulmucha approved these changes

2023-09-03 15:15 UTC, merged